"use client";

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

const AiFeatureMockup = () => {
  const [showAiContent, setShowAiContent] = useState(false);

  const toggleAiContent = () => {
    setShowAiContent(!showAiContent);
  };

  return (
    <div className="py-6"> {/* Added some padding around the whole feature */}
      <Button onClick={toggleAiContent} variant="outline" className="w-full sm:w-auto">
        {showAiContent ? 'Hide AI Assistant Insights' : 'Ask AI Assistant'}
      </Button>

      {showAiContent && (
        <Card className="mt-4 bg-background shadow-lg border-border">
          <CardHeader>
            <CardTitle className="text-xl flex items-center">
              {/* Optional: Sparkles icon or similar if available/desired */}
              {/* <Sparkles className="mr-2 h-5 w-5 text-primary" />  */}
              AI Assistant Insights
            </CardTitle>
            <CardDescription>Powered by Advanced NicheAI™ (Mockup)</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3 text-sm text-foreground">
            <p>• Based on current local trends, the <strong>'{nicheConfig.itemDefinition.fields.find(f => f.key === "style")?.examples?.[0] || "selected style"}'</strong> is gaining popularity in similar properties.</p>
            <p>• Consider pairing this with <strong>'{nicheConfig.itemDefinition.fields.find(f => f.key === "material")?.examples?.[1] || "a complementary material"}'</strong> for a cohesive and modern aesthetic.</p>
            <p>• AI analysis suggests that installation complexity for this item is typically <strong>Moderate</strong>. We can help find qualified local installers for you.</p>
            <p>• Customers interested in this often also explore options for <strong>Energy Star rated upgrades</strong> to maximize efficiency.</p>
            <hr className="my-3 border-border" />
            <p className="text-xs text-muted-foreground">
              Disclaimer: AI insights are for demonstration purposes only and generated by a mockup system. Always consult with a professional for final decisions.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
};

// Minimal nicheConfig structure needed for placeholder text generation
// This is just to make the component self-contained for the example,
// in a real app, this data would likely come from props or context if it needs to be dynamic per item.
const nicheConfig = {
  itemDefinition: {
    fields: [
      { key: "style", examples: ["Sliding Door", "Casement Window"] },
      { key: "material", examples: ["Wood", "Vinyl", "Aluminum"] },
    ]
  }
};

export default AiFeatureMockup;
